config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  
  devise_for :users 
  resources :patients, :medical_records,:doctors,:hospitals,:appointments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  # validates :appointment_date,:appointment_number, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :hospital
  validates :doctor_age,:doctor_fees,:doctor_gender,:doctor_name, :doctor_specialization, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_many :patients, dependent: :destroy
  validates :hospital_name, :hospital_city, :hospital_address, :hospital_type, presence: true
end

app/models/medicalrecord.rb
class Medicalrecord < ApplicationRecord
  belongs_to :patient
  validates :date_of_admit, :date_of_discharge, :doctor_fees, :room_charge, :total_bill, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors , through: :appointments
  has_one :medical_record
  belongs_to :hospital

  validates :patient_name, :patient_address,:patient_age, :patient_disease, :patient_gender, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
    def index
      @appointments = Appointment.all
    end
  
    def new
      @appointment = Appointment.new
    end
  
    def create
      @appointment = Appointment.new(appointment_params)
   
      if @appointment.save
      redirect_to @appointment
      else
        render 'new'
      end
    end
  
    def show
      @appointment = Appointment.find(params[:id])
    end
  
    def edit
      @appointment = Appointment.find(params[:id])
    end
  
    def update
      @appointment = Appointment.find(params[:id])
   
      if @appointment.update(appointment_params)
      redirect_to @appointment
      else
      render 'edit'
      end
    end
  
    def destroy
      @appointment = Appointment.find(params[:id])
      @appointment.destroy
   
      redirect_to appointments_path
    end
  
    private
    def appointment_params
      params.require(:appointment).permit(:appointment_number, :appointment_date)
    end
  
  
  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def index
      @doctors = Doctor.all
    end
  
    def new
      @doctor = Doctor.new
    end
  
    def create
      @doctor = Doctor.new(doctor_params)
   
      if @doctor.save
      redirect_to @doctor
      else
        render 'new'
      end
    end
  
    def show
      @doctor = Doctor.find(params[:id])
    end
  
    def edit
      @doctor = Doctor.find(params[:id])
    end
  
    def update
      @doctor = Doctor.find(params[:id])
   
      if @doctor.update(doctor_params)
      redirect_to @doctor
      else
      render 'edit'
      end
    end
  
    def destroy
      @doctor = Doctor.find(params[:id])
      @doctor.destroy
   
      redirect_to doctors_path
    end
  
    private
    def doctor_params
      params.require(:doctor).permit(:doctor_name, :doctor_age, :doctor_gender, :doctor_specialization,:doctor_fees)
    end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
 
    if @hospital.save
    redirect_to @hospital
    else
      render 'new'
    end
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])
 
    if @hospital.update(hospital_params)
    redirect_to @hospital
    else
    render 'edit'
    end
  end

  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy
 
    redirect_to hospitals_path
  end

  private
  def hospital_params
    params.require(:hospital).permit(:hospital_number,:hospital_name, :hospital_city, :hospital_address, :hospital_type)
  end

end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  def index
    @medical_records = Medicalrecord.all
  end

  def new
    @medical_record = Medicalrecord.new
  end

  def create
    @medical_record = Medicalrecord.new(medicalrecord_params)
 
    if @medical_record.save
      # binding.pry
      redirect_to medical_record_path(@medical_record)
    else
      render 'new'
    end
  end

  def show
    @medical_record = Medicalrecord.find(params[:id])
  end

  def edit
    @medical_record = Medicalrecord.find(params[:id])
  end

  def update
    @medical_record = Medicalrecord.find(params[:id])
 
    if @medical_record.update(medicalrecord_params)
      redirect_to @medical_record
    else
      render 'edit'
    end
  end

  def destroy
    @medical_record = Medicalrecord.find(params[:id])
    @medical_record.destroy
 
    redirect_to medical_records_path
  end

  private
  def medicalrecord_params
    params.require(:medicalrecord).permit(:date_of_admit, :date_of_discharge, :doctor_fees, :room_charge, :total_bill)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
 
    if @patient.save
    redirect_to @patient
    else
      render 'new'
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
 
    if @patient.update(hospital_params)
    redirect_to @patient
    else
    render 'edit'
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
 
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:patient_name, :patient_disease, :patient_address, :patient_age, :patient_gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= form_with model: @appointment, local: true do |form| %>

  <p>
    <%= form.label :appointment_number %><br>
    <%= form.number_field :appointment_number %>
  </p>
 
  <p>
    <%= form.label :appointment_date %><br>
    <%= form.date_field :appointment_date %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit appointment</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>
<%= link_to 'New appointment', new_appointment_path %>
 
<table class="table">
 <thead>
  <tr>
    <th>Number</th>
    <th>Date</th>
  </tr>
 </thead>
 <tbody>
  <% @appointments.each do |appointment| %>

    <tr>
      <td><%= appointment.appointment_number %></td>
      <td><%= appointment.appointment_date %></td>
      <td><%= link_to 'Show', appointment_path(appointment) %></td>
      <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
      <td><%= link_to 'Destroy', appointment_path(appointment),data: {
              turbo_method: :delete,
              turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  
  <% end %>
</tbody>
</table>

app/views/appointments/new.html.erb
<h1>New appointment</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p>
  <strong>appointment_number:</strong>
  <%= @appointment.appointment_number %>
</p>
 
<p>
  <strong>appointment_date:</strong>
  <%= @appointment.appointment_date %>
</p>

 
<%= link_to 'Edit', edit_appointment_path(@appointment) %>
<%= link_to 'Back', appointments_path %>

app/views/doctors/_form.html.erb
<%= form_with model: @doctor, local: true do |form| %>
  <p>
    <%= form.label :doctor_name %><br>
    <%= form.text_field :doctor_name %>
  </p>
 
  <p>
    <%= form.label :doctor_age %><br>
    <%= form.text_field :doctor_age %>
  </p>

  <p>
    <%= form.label :doctor_gender %><br>
    <%= form.text_field :doctor_gender %>
  </p>
 
 <p>
    <%= form.label :doctor_specialization %><br>
    <%= form.text_field :doctor_specialization %>
  </p>
 
 <p>
    <%= form.label :doctor_fees %><br>
    <%= form.text_field :doctor_fees %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit doctor</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>
<%= link_to 'New doctor', new_doctor_path %>
 
<table class="table">
 <thead>
  <tr>
    <th>Name</th>
    <th>Age </th>
    <th>Gender</th>
    <th>Specialization</th>
    <th>Fees</th>
  </tr>
 </thead>
 <tbody>
  <% @doctors.each do |doctor| %>

    <tr>
      <td><%= doctor.doctor_name %></td>
      <td><%= doctor.doctor_age %></td>
      <td><%= doctor.doctor_gender %></td>
      <td><%= doctor.doctor_specialization %></td>
      <td><%= doctor.doctor_fees %></td>
      <td><%= link_to 'Show', doctor_path(doctor) %></td>
      <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
      <td><%= link_to 'Destroy', doctor_path(doctor),data: {
              turbo_method: :delete,
              turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  
  <% end %>
</tbody>
</table>

app/views/doctors/new.html.erb
<h1>New doctor</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p>
  <strong>doctor_name:</strong>
  <%= @doctor.doctor_name %>
</p>
 
<p>
  <strong>doctor_age:</strong>
  <%= @doctor.doctor_age %>
</p>
 
<p>
  <strong>doctor_gender:</strong>
  <%= @doctor.doctor_gender %>
</p>
 
<p>
  <strong>doctor_specialization:</strong>
  <%= @doctor.doctor_specialization %>
</p>
 
<p>
  <strong>doctor_fees:</strong>
  <%= @doctor.doctor_fees %>
</p>
 
<%= link_to 'Edit', edit_doctor_path(@doctor) %>
<%= link_to 'Back', doctors_path %>

app/views/homes/index.html.erb
home page

app/views/hospitals/_form.html.erb
<%= form_with model: @hospital, local: true do |form| %>
   
   <p>
    <%= form.label :hospital_number %><br>
    <%= form.number_field :hospital_number
    %>
  </p>

  <p>
    <%= form.label :Hospital_name %><br>
    <%= form.text_field :hospital_name
    %>
  </p>

  <p>
    <%= form.label :Hospital_city %><br>
    <%= form.text_field :hospital_city %>
  </p>
 
 <p>
    <%= form.label :Hospital_address %><br>
    <%= form.text_field :hospital_address %>
  </p>
 
 <p>
    <%= form.label :Hospital_type %><br>
    <%= form.text_field :hospital_type %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/hospitals/edit.html.erb
<h1>Edit hospital</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<h2>Listing hospital</h2>
<%= link_to 'New hospital', new_hospital_path %> 
 
<table class="table">
 
  <tr>
    <th>Hospital number </th>
    <th>Hospital name </th>
    <th>Hospital city</th>
    <th>Hospital address</th>
    <th>Hospital type</th>
   
  </tr>
 
 
  <% @hospitals.each do |hospital| %>

    <tr>
      <td><%= hospital.hospital_number %></td>
      <td><%= hospital.hospital_name%></td>
      <td><%= hospital.hospital_city %></td>
      <td><%= hospital.hospital_address %></td>
      <td><%= hospital.hospital_type %></td>
      <td><%= link_to 'Show', hospital_path(hospital) %></td>
      <td><%= link_to 'Edit', edit_hospital_path(hospital) %></td>
      <td><%= link_to 'Destroy', hospital_path(hospital), data: { 
              turbo_method: :delete,
              turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  
  <% end %>

</table>

app/views/hospitals/new.html.erb
<h1>New hospital</h1><br>
 
<%= render 'form' %>
 
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p>
  <strong>hospital_number:</strong>
  <%= @hospital.hospital_number %>
</p>
 
<p>
  <strong>Hospital_name:</strong>
  <%= @hospital.hospital_name %>
</p>
 
<p>
  <strong>Hospital_city:</strong>
  <%= @hospital.hospital_city %>
</p>
 
<p>
  <strong>Hospital_address:</strong>
  <%= @hospital.hospital_address %>
</p>
 
<p>
  <strong>Hospital_type:</strong>
  <%= @hospital.hospital_type %>
</p>
 
<%= link_to 'Edit', edit_hospital_path(@hospital) %>
<%= link_to 'Back', hospitals_path %>

app/views/medical_records/_form.html.erb
<%= form_with model: @medical_record, local: true do |form| %>
  <p>
    <%= form.label :Date_of_admit %><br>
    <%= form.date_field :date_of_admit %>
  </p>
 
  <p>
    <%= form.label :date_of_discharge %><br>
    <%= form.date_field :date_of_discharge %>
  </p>

  <p>
    <%= form.label :doctor_fees %><br>
    <%= form.text_field :doctor_fees %>
  </p>
 
 <p>
    <%= form.label :room_charge %><br>
    <%= form.text_field :room_charge %>
  </p>
 
 <p>
    <%= form.label :total_bill %><br>
    <%= form.text_field :total_bill %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Edit medicalrecord</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/index.html.erb
<h1>Listing medicalrecord</h1>
<%= link_to 'New medicalrecord', new_medical_record_path %>
 
<table class="table">
 <thead>
  <tr>
    <th>Admid Date</th>
    <th>Discharge Date </th>
    <th>Doctor Fees</th>
    <th>Room Charge</th>
    <th>Total bill</th>
   
  </tr>
 </thead>
 <tbody>
  <% @medical_records.each do |medical_record| %>

    <tr>
      <td><%= medical_record.date_of_admit %></td>
      <td><%= medical_record.date_of_discharge %></td>
      <td><%= medical_record.doctor_fees %></td>
      <td><%= medical_record.room_charge %></td>
      <td><%= medical_record.total_bill %></td>
      <td><%= link_to 'Show', medical_record_path(medical_record) %></td>
      <td><%= link_to 'Edit', edit_medical_record_path(medical_record) %></td>
      <td><%= link_to 'Destroy', medical_record_path(medical_record),data: { 
              turbo_method: :delete,
              turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  
  <% end %>
</tbody>
</table>

app/views/medical_records/new.html.erb
<h1>new medicalrecord</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/show.html.erb
<p>
  <strong>date_of_admit:</strong>
  <%= @medical_record.date_of_admit %>
</p>
 
<p>
  <strong>date_of_discharge:</strong>
  <%= @medical_record.date_of_discharge %>
</p>
 
<p>
  <strong>doctor_fees:</strong>
  <%= @medical_record.doctor_fees %>
</p>
 
<p>
  <strong>room_charge:</strong>
  <%= @medical_record.room_charge %>
</p>
 
<p>
  <strong>total_bill:</strong>
  <%= @medical_record.total_bill %>
</p>
 
<%= link_to 'Edit', edit_medical_record_path(@medical_record) %>
<%= link_to 'Back', medical_records_path %>

app/views/patients/_form.html.erb
<%= form_with model: @patient, local: true do |form| %>
  <p>
    <%= form.label :patient_name %><br>
    <%= form.text_field :patient_name %>
  </p>
 
  <p>
    <%= form.label :patient_age %><br>
    <%= form.text_field :patient_age %>
  </p>

  <p>
    <%= form.label :patient_gender %><br>
    <%= form.text_field :patient_gender %>
  </p>
 
 <p>
    <%= form.label :patient_address %><br>
    <%= form.text_field :patient_address %>
  </p>
 
 <p>
    <%= form.label :patient_disease %><br>
    <%= form.text_field :patient_disease %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit patient</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>
<%= link_to 'New patient', new_patient_path %>
 
<table class="table">
 <thead>
  <tr>
    <th>Name</th>
    <th>Age </th>
    <th>Gender</th>
    <th>Address</th>
    <th>Disease</th>
  </tr>
 </thead>
 <tbody>
  <% @patients.each do |patient| %>

    <tr>
      <td><%= patient.patient_name %></td>
      <td><%= patient.patient_age %></td>
      <td><%= patient.patient_gender %></td>
      <td><%= patient.patient_address %></td>
      <td><%= patient.patient_disease %></td>
      <td><%= link_to 'Show', patient_path(patient) %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      <td><%= link_to 'Destroy', patient_path(patient), data: { 
              turbo_method: :delete,
              turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  
  <% end %>
</tbody>
</table>

app/views/patients/new.html.erb
<h1>New patient</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p>
  <strong>patient_name:</strong>
  <%= @patient.patient_name %>
</p>
 
<p>
  <strong>patient_age:</strong>
  <%= @patient.patient_age %>
</p>
 
<p>
  <strong>patient_gender:</strong>
  <%= @patient.patient_gender %>
</p>
 
<p>
  <strong>patient_address:</strong>
  <%= @patient.patient_address %>
</p>
 
<p>
  <strong>patient_disease:</strong>
  <%= @patient.patient_disease %>
</p>
 
<%= link_to 'Edit', edit_patient_path(@patient) %>
<%= link_to 'Back', patients_path %>